FROM docker.n8n.io/n8nio/n8n:latest

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=development-datacode.j.aivencloud.com
ENV DB_POSTGRESDB_PORT=15555
ENV DB_POSTGRESDB_DATABASE=defaultdb
ENV DB_POSTGRESDB_USER=avnadmin
ENV DB_POSTGRESDB_PASSWORD=AVNS_KDMqDAKw2I13Rr776
ENV DB_SSL=true
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV GENERIC_TIMEZONE=Asia/Kolkata

EXPOSE 5678

ENTRYPOINT ["n8n"]

